### ISSUE TITLE
Too slow joint-training

### ISSUE THREAD

**Issue by sjtuytc** [ehsanik/touchTorch#1]
Hi, I sincerely appreciate your open-sourced code. However, when I tried to run 
`python main.py --title joint_training --sequence_length 10 --gpu-ids 0 --number_of_cp 5 --model SeparateTowerModel --dataset DatasetWAugmentation --loss KPProjectionCPPredictionLoss --object_list ALL --data DatasetForce --batch-size 1 train`
the speed is too low that it needs more over 4 hours for an epoch on an 1080TI gpu with 20 cpu cores. Is that all right?

**Comment by ehsanik** [comment]
Yes this is correct. Because of calculating the finite differencing on the output of the physics simulation for each step there needs to be (13+3*5+3*5) calls to the pybullet. Note that this is a cpu-heavy process and is not run on GPUs. However, by paying the price of slow training we are able to train our model without Force supervision.

**Comment by sjtuytc** [comment]
It seems that you don't support batch_size > 1 currently, what's the problem? Did you try to use vec_env to run multiple environments parallelly?
