### ISSUE TITLE
Inaccurate gt keypoints annotation.

### ISSUE THREAD

**Issue by sjtuytc** [ehsanik/touchTorch#5]
Hi, in DatasetForce/images/035_power_drill/image_16063_2019_09_13_15_51_12_703202.jpeg and DatasetForce/images/035_power_drill/image_16067_2019_09_13_15_51_12_818194.jpeg, the keypoints annotation is very coarse. Why is that? What can we do?
![2000_gt_kp](https://user-images.githubusercontent.com/31123348/81804125-3a372600-954b-11ea-9323-fcd09bb5c59a.jpg)

**Comment by ehsanik** [comment]
As mentioned in our paper, the keypoint annotation can be noisy due to errors from our annotators. While we test our annotators with an initial quiz to make sure they understand the task correctly, there might still be some unavoidable mistakes in the annotation. However, this is a rare situation. If you look at the neighboring frames, they are all pretty accurate. 
![ezgif-2-646bf17fc4c8](https://user-images.githubusercontent.com/6522430/81998691-07069c80-9608-11ea-9602-565b23131864.gif)
